services:
  caddy:
    image: caddy:2.7.6-alpine # Use a stable version
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./web:/var/web

  backend:
    ports:
      - "8080:8080"
    build:
      context: backend
      target: builder

volumes:
  caddy_data:
  caddy_config:

